# Generated by Django 4.2.2 on 2023-06-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
