# Generated by Django 4.2.2 on 2023-06-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
